# ==============================================================================
# 1. SITE DATA
# ==============================================================================
title: Rabbi On Rails
logo: /assets/images/logo.png
email: contact@yechiel.me
description: >- 
  Rabbi on Rails: where I pontificate on matters related to Judaism, tech, career, ethical AI and more.
url: "https://blog.yechiel.me" 
baseurl: "" 
timezone: "America/New_York"
repository: "achasveachas/rabbi-on-rails"

# ==============================================================================
# 2. AUTHOR PROFILE
# ==============================================================================
author:
  name     : "Yechiel Kalmenson"
  # avatar   : "/assets/images/avatar.jpg" 
  bio      : "Coding With the Masters"
  location : "New York"
  links:
    - label: "Personal Website"
      icon: "fas fa-fw fa-link"
      url: "https://yechiel.me"
    - label: "Email"
      icon: "fas fa-fw fa-envelope" 
      url: "mailto:contact@yechiel.me"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/achasveachas"
    - label: "Dev.to"
      icon: "fab fa-fw fa-dev"
      url: "https://dev.to/yechielk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yechiel-k"

# ==============================================================================
# 3. THEME SETTINGS (Minimal Mistakes)
# ==============================================================================
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"
search: true
search_provider: lunr

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true 
      read_time: true 
      show_date: true

# ==============================================================================
# 4. BUILD & ENVIRONMENT SETTINGS
# ==============================================================================
paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/